// generated by narrate.mjs — do not edit
const TIMELINE = {
 "title": "Sāvitrī & Satyavān",
 "subtitle": "Mahābhārata · Vana Parva 291–297",
 "total": 121.9,
 "scenes": [
  {
   "id": "choice",
   "name": "The Choice",
   "display": "The princess Sāvitrī shone so brightly that no prince dared ask for her hand. So she went forth to choose for herself — and in a forest hermitage she chose Satyavān, son of a blind and exiled king.",
   "mood": "mystic",
   "start": 0,
   "narrAt": 2.2,
   "narrDur": 13.316,
   "dur": 16.716,
   "end": 16.716
  },
  {
   "id": "prophecy",
   "name": "Nārada's Word",
   "display": "But the sage Nārada told her father: this youth is flawless in every virtue — and one year from this day, he will die. Sāvitrī answered only: \"The heart is given once. I have given mine.\"",
   "mood": "somber",
   "start": 16.716,
   "narrAt": 17.716,
   "narrDur": 12.551,
   "dur": 14.751,
   "end": 31.467
  },
  {
   "id": "year",
   "name": "Counting the Days",
   "display": "She put away her silks, wore bark-cloth, and served the hermitage — telling no one, counting the days. For the last three nights she stood fasting, still as a lamp in windless air.",
   "mood": "tender",
   "start": 31.467,
   "narrAt": 32.467,
   "narrDur": 11.837,
   "dur": 14.037,
   "end": 45.504
  },
  {
   "id": "axe",
   "name": "The Fated Day",
   "display": "On the appointed morning she followed him into the forest. At noon, the axe slipped from Satyavān's hand. \"My head,\" he said, \"is splitting.\" And he laid it in her lap, and was still.",
   "mood": "suspense",
   "start": 45.504,
   "narrAt": 46.504,
   "narrDur": 12.529,
   "dur": 15.129,
   "end": 60.633
  },
  {
   "id": "yama",
   "name": "The Dark King",
   "display": "Then Sāvitrī saw a figure dark as a rain-cloud, robed in red, a noose in his hand: Yama, King of the Dead, come in person for so virtuous a soul. He drew out a spark the size of a thumb — and turned south. And she followed.",
   "mood": "somber",
   "start": 60.633,
   "narrAt": 61.833,
   "narrDur": 15.146,
   "dur": 17.946,
   "end": 78.579
  },
  {
   "id": "boons",
   "name": "Walking with Death",
   "display": "Walk with the wise but seven steps, she said, and you are friends. Pleased, Yama offered boons — anything but the life he carried. Sight for the blind king. A kingdom restored. And then: \"a hundred sons, born of me and Satyavān.\" The Lord of Death stopped walking.",
   "mood": "tense",
   "start": 78.579,
   "narrAt": 79.579,
   "narrDur": 18.262,
   "dur": 20.862,
   "end": 99.441
  },
  {
   "id": "return",
   "name": "The Return",
   "display": "For her word could not come true unless his life was returned. Caught by his own boon, Yama smiled — and loosed the noose. Satyavān woke as if from sleep; his father's eyes opened on the world; and Sāvitrī walked her husband home at dusk, having out-argued Death.",
   "mood": "triumphant",
   "start": 99.441,
   "narrAt": 100.641,
   "narrDur": 17.058,
   "dur": 22.458,
   "end": 121.9
  }
 ]
};
