// generated by narrate.mjs — do not edit
const TIMELINE = {
 "title": "The Winning of Draupadī",
 "subtitle": "Mahābhārata · Ādi Parva 166–198",
 "total": 171.245,
 "scenes": [
  {
   "id": "fire",
   "name": "Born of Fire",
   "display": "In the kingdom of Pañchāla, King Drupada kindled a great sacrificial fire, and out of the flames rose a daughter — dark, radiant, born of no womb at all. Her name was Draupadī. The gods whispered that she would bend the fate of kings.",
   "start": 0,
   "narrAt": 2.6,
   "narrDur": 18.85,
   "dur": 23.65,
   "end": 23.65
  },
  {
   "id": "hall",
   "name": "The Svayaṃvara",
   "display": "When she came of age, kings from every land filled Drupada's hall. High above hung a golden fish, spinning on a wheel. Whoever could string the great bow, and pierce the fish's eye by its reflection alone, would win her hand.",
   "start": 23.65,
   "narrAt": 25.45,
   "narrDur": 17.748,
   "dur": 21.748,
   "end": 45.398
  },
  {
   "id": "kings",
   "name": "The Kings Fail",
   "display": "One by one, the proud kings strained against the bow — and one by one they fell back, defeated. Even Karṇa the golden rose to try; but Draupadī turned her face away.",
   "start": 45.398,
   "narrAt": 47.198,
   "narrDur": 13.8,
   "dur": 17.8,
   "end": 63.198
  },
  {
   "id": "rises",
   "name": "A Stranger in White",
   "display": "Then, from among the brahmins, a quiet young man in white rose to his feet — one of the five Pāṇḍava brothers the world believed dead in the burning of the lac house. His name was Arjuna.",
   "start": 63.198,
   "narrAt": 64.998,
   "narrDur": 13.386,
   "dur": 17.586,
   "end": 80.784
  },
  {
   "id": "shot",
   "name": "The Eye of the Fish",
   "display": "He circled the bow, and bowed his head. In a single breath he strung it. Then, gazing only into the water — at the trembling reflection of the wheel — he loosed five arrows into the sky.",
   "start": 80.784,
   "narrAt": 82.784,
   "narrDur": 14.58,
   "dur": 20.58,
   "end": 101.364
  },
  {
   "id": "garland",
   "name": "The Garland",
   "display": "The golden fish fell. And Draupadī came to the stranger, and laid her garland of white flowers upon his neck. In the crowd, Kṛṣṇa smiled — for he alone had recognized the brahmin.",
   "start": 101.364,
   "narrAt": 103.164,
   "narrDur": 14.873,
   "dur": 19.073,
   "end": 120.438
  },
  {
   "id": "kunti",
   "name": "A Mother's Word",
   "display": "That evening, at their mother's door, the brothers called out: \"Mother — see what we have brought!\" And Kuntī, without turning, answered: \"Share it among yourselves.\" A mother's word, once spoken, could not be unsaid.",
   "start": 120.438,
   "narrAt": 122.238,
   "narrDur": 18.863,
   "dur": 23.263,
   "end": 143.7
  },
  {
   "id": "wedding",
   "name": "Five Flames, One Fate",
   "display": "But the sage Vyāsa unfolded a deeper design: in a life before this one, Draupadī had prayed to Lord Śiva five times for a worthy husband, and Śiva had granted every prayer. So Draupadī wed all five Pāṇḍava brothers, and their fates were bound together until the end of the age.",
   "start": 143.7,
   "narrAt": 145.5,
   "narrDur": 20.945,
   "dur": 27.545,
   "end": 171.245
  }
 ]
};
