// generated by narrate.mjs — do not edit
const TIMELINE = {
 "title": "Govardhana",
 "subtitle": "Bhāgavata Purāṇa · Canto X.24–27",
 "total": 98.651,
 "scenes": [
  {
   "id": "pastoral",
   "name": "The Herders' Festival",
   "display": "In Vṛndāvana the cowherds kept a festival for Indra, lord of rain. But young Kṛṣṇa watched the cattle graze the green slopes of Govardhana, and wondered why the mountain that fed them went unthanked.",
   "mood": "festive",
   "start": 0,
   "narrAt": 2.2,
   "narrDur": 11.92,
   "dur": 15.42,
   "end": 15.42
  },
  {
   "id": "counsel",
   "name": "Worship What Feeds You",
   "display": "\"Worship what feeds you,\" said Kṛṣṇa. \"These pastures, these cows, this hill — they give us all we have. Honour Govardhana, and let the pride of distant Indra go.\" And the herders, trusting, agreed.",
   "mood": "tender",
   "start": 15.42,
   "narrAt": 16.42,
   "narrDur": 14.011,
   "dur": 16.311,
   "end": 31.731
  },
  {
   "id": "fury",
   "name": "Indra's Wrath",
   "display": "Robbed of his worship, Indra raged. He loosed the clouds of doomsday upon Vṛndāvana — seven nights of blinding rain, thunder without mercy, to drown the herders and their impudent cowherd boy.",
   "mood": "tense",
   "start": 31.731,
   "narrAt": 32.731,
   "narrDur": 12.271,
   "dur": 14.671,
   "end": 46.402
  },
  {
   "id": "lift",
   "name": "The Lifting of the Mountain",
   "display": "Then Kṛṣṇa reached down, and lifted Govardhana whole upon his little finger. The mountain rose like a vast green umbrella — and all Vṛndāvana, herder and cow and calf, sheltered beneath it, dry.",
   "mood": "triumphant",
   "start": 46.402,
   "narrAt": 47.802,
   "narrDur": 12.906,
   "dur": 17.706,
   "end": 64.108
  },
  {
   "id": "vigil",
   "name": "Seven Days and Nights",
   "display": "Seven days and seven nights the rain hammered the world. Yet under the mountain not one drop fell. Kṛṣṇa held it steady, smiling, while the storm spent its fury on the unbroken circle of calm.",
   "mood": "mystic",
   "start": 64.108,
   "narrAt": 65.108,
   "narrDur": 12.97,
   "dur": 16.17,
   "end": 80.278
  },
  {
   "id": "govinda",
   "name": "Govinda",
   "display": "At last Indra's storm broke, and shamed, he bowed. The sun returned to a washed and shining Vṛndāvana. Kṛṣṇa set the mountain down — and the cowherds hailed him Govinda, keeper of cows.",
   "mood": "festive",
   "start": 80.278,
   "narrAt": 81.478,
   "narrDur": 12.973,
   "dur": 18.373,
   "end": 98.651
  }
 ]
};
